sudo: required #관리자 권한 갖기

language: generic #언어(플랫폼)을 선택 ex) node, python...

service: #도커 환경 구성
  - docker

before_install: #스크립트를 실행할 수 있는 환경 구성(테스트 실행 하기 전)
  - echo "start Creating an image with dockerfile" 
  - docker build -t bsoy0530/docker-react-app -f Dockerfile.dev . #도커 파일을 이용해 이미지 생성

script: #실행할 스크립트(테스트 실행)
  - docker run -e CI=true bsoy0530/docker-react-app npm run test -- --coverage
#travis CI에서 -e CI=true 가 없으면 에러가 남!
#-- --coverage : 테스트 더욱 상세하게 하기 위해

after_success: #테스트 성공 후 할 일
  - echo "Test Success"