FROM node:alpine

WORKDIR /usr/src/app

COPY package.json ./

RUN npm install

COPY ./ ./

CMD ["npm", "run", "start"]

#Dockerfile이 아닌 Dockerfile.dev가 존재하기 때문에 그냥 빌드하면 에러가 나옴
## 따라서, docker build -f Dockerfile.dev ./ 를 사용하여 빌드
### -f: 이미지를 빌드할 때 쓰일 도커파일을 임의로 지정

#도커 환경에서는 로컬의 node_modules가 필요하지 않음.
## 왜냐? package.json안의 dependencies에 쓰여져 있기 때문
## 이미 npm install때 node_modules이 컨테이너 안에 존재하게 되었는데, COPY ./ ./ 명령어로 또 node_modules를 복사하기 때문에 오히려 빌드 시간이 더 늘어남
## 그러기에 node_modules를 지워주어도 됨~

#docker run -p 3000:3000 [이미지이름]  안먹을 경우..
## docker run -it -p 3000:3000 [이미지이름] 으로 실행
### -i: 상호 입출력 / -t: tty를 활성화하여 bash쉘을 사용

#volume 사용하여 실행(매핑, 빌드 안하고 소스코드 수정해도 반영되게...)
## docker run -p 3000:3000 -v /usr/src/app/node_modules -v $(pwd):/usr/src/app bsy0530/docker-react-app

#도커에서 테스트 하는 법
## docker run -it bsy0530/docker-react-app npm run test